apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: ds-projects
  labels:
    app: rag-api
spec:
  selector:
    app: rag-api
  ports:
    - name: gradio
      port: 80
      targetPort: 7860
      protocol: TCP
  type: ClusterIP
