"""
Определения фичей для Feast Feature Store — RecSys проект.
Feast Feature definitions for the RecSys e-commerce recommendation system.

Этот файл — единственный источник правды для схем фичей (registry as code).
This file is the single source of truth for feature schemas (registry as code).

Запуск materialize / Run materialize:
    feast -c feature_repo apply
    feast -c feature_repo materialize-incremental $(date +%Y-%m-%dT%H:%M:%S)

Получение фичей в коде / Get features in code:
    from feast import FeatureStore
    store = FeatureStore(repo_path="feature_repo")
    features = store.get_online_features(
        features=["user_features:avg_rating", "user_features:n_purchases"],
        entity_rows=[{"user_id": 42}],
    ).to_dict()

Без Feast (наш FeastBridge) / Without Feast (our FeastBridge):
    from recsys.feature_store.feast_bridge import FeastBridge, FeatureRequest
    bridge = FeastBridge(registry=populated_registry)
    resp = bridge.get_online_features(FeatureRequest(
        entity_rows=[{"user_id": 42}],
        features=["user_features:avg_rating", "user_features:n_purchases"],
    ))

Sources:
  - Feast feature view docs: docs.feast.dev/getting-started/concepts/feature-view
  - Made With ML feature store: madewithml.com/courses/mlops/feature-store
"""

from __future__ import annotations

# Feast импортируется условно — файл должен читаться без Feast в окружении.
# Feast is imported conditionally — this file should be importable without Feast.
try:
    from datetime import timedelta

    from feast import Entity, FeatureView, Field, FileSource
    from feast.types import Float64, Int64, String

    # ------------------------------------------------------------------
    # Entities — ключевые сущности / Key entities
    # ------------------------------------------------------------------

    user_entity = Entity(
        name="user_id",
        description="Пользователь e-commerce платформы / E-commerce platform user",
    )

    item_entity = Entity(
        name="product_id",
        description="Товар / Product in the catalog",
    )

    # ------------------------------------------------------------------
    # Sources — источники данных / Data sources
    # ------------------------------------------------------------------

    # Parquet-файлы генерируются offline pipeline (offline.py → save_features_parquet)
    # Parquet files are generated by the offline pipeline
    user_source = FileSource(
        path="data/features/user_features.parquet",
        timestamp_field="event_timestamp",
        description="Offline user features from interaction history",
    )

    item_source = FileSource(
        path="data/features/item_features.parquet",
        timestamp_field="event_timestamp",
        description="Offline item features from rating data",
    )

    # ------------------------------------------------------------------
    # Feature Views — представления фичей / Feature views
    # ------------------------------------------------------------------

    user_features_view = FeatureView(
        name="user_features",
        entities=[user_entity],
        ttl=timedelta(days=7),  # фичи актуальны 7 дней / features valid for 7 days
        schema=[
            Field(name="avg_rating", dtype=Float64, description="Средний рейтинг пользователя"),
            Field(name="n_purchases", dtype=Int64, description="Количество взаимодействий"),
            Field(name="favorite_category", dtype=String, description="Любимая категория"),
            Field(name="recency_days", dtype=Int64, description="Дней с последнего взаимодействия"),
        ],
        source=user_source,
        description="User behaviour features computed from interaction history",
        tags={"team": "recsys", "project": "09-recsys-feature-store"},
    )

    item_features_view = FeatureView(
        name="item_features",
        entities=[item_entity],
        ttl=timedelta(days=1),  # товарные фичи обновляются чаще / item features updated more often
        schema=[
            Field(name="item_avg_rating", dtype=Float64, description="Средний рейтинг товара"),
            Field(name="n_ratings", dtype=Int64, description="Количество оценок"),
            Field(name="popularity_rank", dtype=Int64, description="Ранг популярности"),
        ],
        source=item_source,
        description="Item popularity features computed from rating data",
        tags={"team": "recsys", "project": "09-recsys-feature-store"},
    )

    # ------------------------------------------------------------------
    # Export for feast apply
    # ------------------------------------------------------------------
    __all__ = [
        "user_entity",
        "item_entity",
        "user_features_view",
        "item_features_view",
    ]

except ImportError:
    # Feast не установлен — определения недоступны в runtime,
    # но FeastBridge работает независимо через FeatureRegistry.
    # Feast not installed — definitions unavailable at runtime,
    # but FeastBridge works independently via FeatureRegistry.
    __all__ = []
