apiVersion: v1
kind: Service
metadata:
  name: quality-api
  namespace: ds-projects
  labels:
    app: quality-api
spec:
  selector:
    app: quality-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
